apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: node-maintenance-operator
  namespace: openshift-operator-lifecycle-manager
spec:
  sourceType: grpc
  image: quay.io/fromani/node-maintenance-operator-registry:latest
  displayName: node-maintenance-operator
  publisher: Red hat