apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: node-maintenance-operator
    control-plane: controller-manager
    node-maintenance-operator: ""
  name: node-maintenance-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: node-maintenance-operator
    control-plane: controller-manager
    node-maintenance-operator: ""
status:
  loadBalancer: {}
