apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: node-maintenance-operator
    node-maintenance-operator: ""
  name: node-maintenance-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: node-maintenance-operator
    control-plane: controller-manager
    node-maintenance-operator: ""
status:
  loadBalancer: {}
