apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: node-maintenance-operator
  namespace: olm
spec:
  sourceType: grpc
  image: quay.io/kubevirt/node-maintenance-operator-index:latest
