---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: nodemaintenances.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: NodeMaintenance
    listKind: NodeMaintenanceList
    plural: nodemaintenances
    singular: nodemaintenance
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            nodeName:
              type: string
            reason:
              type: string
          required:
          - nodeName
          type: object
        status:
          properties:
            phase:
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: node-maintenance-operator
  labels:
    name: node-maintenance-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    name: node-maintenance-operator
  name: node-maintenance-operator
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - events
  - configmaps
  - serviceaccounts  
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
  - patch 
  - watch  
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch  
- apiGroups:
  - ""  
  resources:
  - pods/eviction
  verbs:
  - create        
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - kubevirt.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - oauth.openshift.io
  resources:
  - '*'
  verbs:
  - '*' 
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-maintenance-operator
subjects:
- kind: ServiceAccount
  name: node-maintenance-operator
  namespace: node-maintenance-operator
roleRef:
  kind: ClusterRole
  name: node-maintenance-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-maintenance-operator
  namespace: node-maintenance-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-maintenance-operator
  namespace: node-maintenance-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-maintenance-operator
  template:
    metadata:
      labels:
        name: node-maintenance-operator
    spec:
      serviceAccountName: node-maintenance-operator
      nodeSelector:
        "node-role.kubernetes.io/infra": "true"
      containers:
        - name: node-maintenance-operator
          # Replace this with the built image name
          image: quay.io/kubevirt/node-maintenance-operator:v0.1.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "node-maintenance-operator"
