apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodemaintenances.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: NodeMaintenance
    listKind: NodeMaintenanceList
    plural: nodemaintenances
    singular: nodemaintenance
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            nodeName:
              description: Node name to apply maintanance on/off
              type: string
            reason:
              description: Reason for maintanance
              type: string
          required:
          - nodeName
          type: object
        status:
          properties:
            completed:
              description: Completed represents the state of maintenance. True if
                completed , false otherwise
              type: boolean
            errorMessage:
              description: ErrorMessage represents the latest reason for failed=true
              type: string
            failed:
              description: Failed is true if the controller did not complete maintenance
                during the latest reconciliation, false otherwise
              type: boolean
            pendingPods:
              description: PendingPods are pods that failed to be evicted in the latest
                reconciliation
              items:
                type: object
              type: array
            startTime:
              description: StartTime contains the Date and time at which the maintenance
                CR processing has started
              format: date-time
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
