apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"kubevirt.io/v1alpha1","kind":"NodeMaintenance","metadata":{"name":"nodemaintenance-xyz"},"spec":{"nodeName":"node02","reason":"Test
      node maintenance"}}]'
    capabilities: Basic Install
  name: node-maintenance-operator.v0.3.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: NodeMaintenance
      name: nodemaintenances.kubevirt.io
      version: v1alpha1
  description: Placeholder description
  displayName: Node Maintenance Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - services
          - endpoints
          - events
          - configmaps
          - serviceaccounts
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
          - update
          - patch
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - pods/eviction
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - kubevirt.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - oauth.openshift.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: node-maintenance-operator
      deployments:
      - name: node-maintenance-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: node-maintenance-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: node-maintenance-operator
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: node-role.kubernetes.io/master
                        operator: Exists
              containers:
              - env:
                - name: WATCH_NAMESPACE
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: node-maintenance-operator
                image: quay.io/kubevirt/node-maintenance-operator:v0.3.0
                imagePullPolicy: Always
                name: node-maintenance-operator
                resources: {}
              serviceAccountName: node-maintenance-operator
              tolerations:
              - effect: NoSchedule
                key: node-role.kubernetes.io/master
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.3.0
