apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: node-maintenance
  namespace: marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: kubevirt
  displayName: "KubeVirt Node Maintenance"
  publisher: "KubeVirt project"