name: Publish Container Images
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  push-images:
    name: Build and push images to quay.io/medik8s
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Build and push CSV 0.0.1 + latest images for PR merges to main
        if: ${{ github.ref_type != 'tag' }}
        run: export IMAGE_REGISTRY=quay.io/medik8s && make container-build-and-push

      - name: Build and push versioned CSV and images for tags
        if: ${{ github.ref_type == 'tag' }}
        # remove leading 'v' from tag!
        run: export IMAGE_REGISTRY=quay.io/medik8s && export VERSION=$(echo $GITHUB_REF_NAME | sed 's/v//') && make container-build-and-push
