name: Tests and build open and merged PRs
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
jobs:
  test-and-build:
    name: Test and build PRs
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run checks and unit tests
      run: make check

    - name: Build images
      run: make container-build
